---
rubygems:
  - train-winrm

slack:
  notify_channel: train-notify

github:
  version_tag_format: "v{{version}}"
  minor_bump_labels:
    - "Expeditor/Bump Minor Version"
  major_bump_labels:
    - "Expeditor/Bump Major Version"

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor/Skip Version Bump"
        - "Expeditor/Skip All"
  - bash:.expeditor/update_version.sh:
      only_if:
        - built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor/Skip Changelog"
        - "Expeditor/Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version

promote:
  actions:
    - built_in:rollover_changelog
    - built_in:publish_rubygems
